# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-23 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20180610_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Aadhaar Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number'),
        ),
    ]
