# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-29 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20181027_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhaar_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Aadhaar Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Mobile Number'),
        ),
    ]
