# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20181029_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Custom Role'),
        ),
    ]
