# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-13 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_add_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='accident_causes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Accident Causes'),
        ),
        migrations.AddField(
            model_name='issue',
            name='accident_classification',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Accident Classification'),
        ),
        migrations.AddField(
            model_name='issue',
            name='accident_date',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Accident Date'),
        ),
        migrations.AddField(
            model_name='issue',
            name='accident_nature',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Accident Nature'),
        ),
        migrations.AddField(
            model_name='issue',
            name='accident_time',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Accident Time'),
        ),
        migrations.AddField(
            model_name='issue',
            name='affected_persons_fatal',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Affected Persons Fatal'),
        ),
        migrations.AddField(
            model_name='issue',
            name='affected_persons_grievous',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Affected persons grievous'),
        ),
        migrations.AddField(
            model_name='issue',
            name='affected_persons_minor',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Affected persons minor'),
        ),
        migrations.AddField(
            model_name='issue',
            name='affected_persons_non_injured',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Affected persons non injured'),
        ),
        migrations.AddField(
            model_name='issue',
            name='animals_killed',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Animals killed'),
        ),
        migrations.AddField(
            model_name='issue',
            name='chainage_from',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chainage From'),
        ),
        migrations.AddField(
            model_name='issue',
            name='chainage_side',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chainage Side'),
        ),
        migrations.AddField(
            model_name='issue',
            name='chainage_to',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chainage To'),
        ),
        migrations.AddField(
            model_name='issue',
            name='help_provided',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Help Provided'),
        ),
        migrations.AddField(
            model_name='issue',
            name='intersection_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Intersection Type'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_category',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Issue Category'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_subcategory',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Issue Subcategory'),
        ),
        migrations.AddField(
            model_name='issue',
            name='quantity',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='issue',
            name='road_condition',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Road Condition'),
        ),
        migrations.AddField(
            model_name='issue',
            name='road_feature',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Road Feature'),
        ),
        migrations.AddField(
            model_name='issue',
            name='treatment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Treatment'),
        ),
        migrations.AddField(
            model_name='issue',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Unit Of Measurement'),
        ),
        migrations.AddField(
            model_name='issue',
            name='vehicle_responsible',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Vehicle Responsible'),
        ),
        migrations.AddField(
            model_name='issue',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Weather Condition'),
        ),
    ]
