# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20181113_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Issue Id'),
        ),
    ]
