# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-20 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_issue_issue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_id',
            new_name='formatted_issue_id',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_id_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Issue Id_Count'),
        ),
    ]
