# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-29 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_issue_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='inspection_category',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Inspection Category'),
        ),
    ]
