# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-31 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_issue_inspection_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='compliance_is_update',
            field=models.BooleanField(default=False),
        ),
    ]
