# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_issue_compliance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='acceptable',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Acceptable'),
        ),
        migrations.AddField(
            model_name='issue',
            name='asset_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Asset Type'),
        ),
        migrations.AddField(
            model_name='issue',
            name='desirable',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Desirable'),
        ),
        migrations.AddField(
            model_name='issue',
            name='frequency',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='issue',
            name='investigation_date',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Investigation Date'),
        ),
        migrations.AddField(
            model_name='issue',
            name='investigation_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Investigation Description'),
        ),
        migrations.AddField(
            model_name='issue',
            name='test_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Test Name'),
        ),
        migrations.AddField(
            model_name='issue',
            name='test_specifications',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Test Specification'),
        ),
    ]
