# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-03 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_auto_20190503_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Image Url'),
        ),
    ]
