# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-03 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0018_issue_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='investigation_chainage_from',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Investigation Chainage From'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='investigation_chainage_side',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Investigation Chainage Side'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='investigation_chainage_to',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Investigation Chainage To'),
        ),
    ]
