# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-03 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0019_auto_20190503_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='file',
            field=models.FileField(default='null', upload_to='', verbose_name='File'),
        ),
    ]
