# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-03 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0020_issue_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='file',
        ),
    ]
