# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-28 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0021_remove_issue_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='standard_reference',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Standard Reference'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tesing_method',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Testng Method'),
        ),
    ]
