# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-28 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0022_auto_20190528_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='tesing_method',
            new_name='testing_method',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='standard_reference',
        ),
    ]
