# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_auto_20181030_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='O_M_handover_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='O & M handover date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='appointed_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Appointed Date O & M Handover Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_of_signing_of_concession_agreement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Date of signing of Concession Agreement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scheduled_end_of_concession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Scheduled End of Concession'),
        ),
    ]
