# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-04 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20181121_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(max_length=250, verbose_name='name'),
        ),
    ]
