# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_auto_20190504_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
    ]
